@extends('layouts.sidebar')

@section('title', 'User Reports')

@section('heading', 'User Reports')

@section('heading_buttons')
<div>
    <a href="{{ route('reports.index') }}" class="btn btn-outline-secondary">
        <i class="fas fa-arrow-left"></i> Back to Reports
    </a>
</div>
@endsection

@section('content')
<div class="row mb-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Generate User Report</h5>
            </div>
            <div class="card-body">
                <form action="{{ route('reports.users') }}" method="POST" class="row g-3">
                    @csrf
                    
                    <div class="col-md-4">
                        <label for="role" class="form-label">User Role</label>
                        <select class="form-select" id="role" name="role">
                            <option value="">All Roles</option>
                            <option value="public">Public Users</option>
                            <option value="agency">Agency Users</option>
                            <option value="mcmc">MCMC Users</option>
                        </select>
                    </div>
                    
                    <div class="col-md-4">
                        <label for="status" class="form-label">Account Status</label>
                        <select class="form-select" id="status" name="status">
                            <option value="">All Statuses</option>
                            <option value="active">Active</option>
                            <option value="inactive">Inactive</option>
                        </select>
                    </div>
                    
                    <div class="col-md-4">
                        <label for="report_type" class="form-label">Report Type</label>
                        <select class="form-select" id="report_type" name="report_type" required>
                            <option value="detailed">Detailed Report</option>
                            <option value="summary">Summary Report</option>
                        </select>
                    </div>
                    
                    <div class="col-md-4">
                        <label for="date_from" class="form-label">Registration Date From</label>
                        <input type="date" class="form-control" id="date_from" name="date_from">
                    </div>
                    
                    <div class="col-md-4">
                        <label for="date_to" class="form-label">Registration Date To</label>
                        <input type="date" class="form-control" id="date_to" name="date_to">
                    </div>
                    
                    <div class="col-md-4">
                        <label for="format" class="form-label">Format</label>
                        <select class="form-select" id="format" name="format" required>
                            <option value="pdf">PDF</option>
                            <option value="excel">Excel</option>
                            <option value="csv">CSV</option>
                        </select>
                    </div>
                    
                    <div class="col-12 d-flex justify-content-end">
                        <button type="submit" class="btn btn-mcmc">Generate Report</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Recent User Reports</h5>
            </div>
            <div class="card-body">
                @if($reports->count() > 0)
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Report Name</th>
                                    <th>Type</th>
                                    <th>Generated By</th>
                                    <th>Date</th>
                                    <th>Format</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($reports as $report)
                                    <tr>
                                        <td>{{ $report->name }}</td>
                                        <td>{{ ucfirst($report->type) }}</td>
                                        <td>{{ $report->user->name }}</td>
                                        <td>{{ $report->created_at->format('d M Y, h:i A') }}</td>
                                        <td>{{ strtoupper($report->format) }}</td>
                                        <td>
                                            <a href="{{ route('reports.show', $report) }}" class="btn btn-sm btn-mcmc">View</a>
                                            <a href="{{ route('reports.download', $report) }}" class="btn btn-sm btn-outline-primary">Download</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    
                    <div class="d-flex justify-content-center mt-4">
                        {{ $reports->links() }}
                    </div>
                @else
                    <div class="text-center py-4">
                        <i class="fas fa-file-alt fa-3x text-gray-300 mb-3"></i>
                        <p class="mb-0">No user reports found.</p>
                        <p>Generate a new report using the form above.</p>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>

<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">User Statistics</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="card border-left-primary h-100">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="text-uppercase text-primary fw-bold">Total Users</h6>
                                        <h2 class="mb-0">{{ $totalUsers }}</h2>
                                    </div>
                                    <i class="fas fa-users fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card border-left-success h-100">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="text-uppercase text-success fw-bold">Active Users</h6>
                                        <h2 class="mb-0">{{ $activeUsers }}</h2>
                                    </div>
                                    <i class="fas fa-user-check fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card border-left-info h-100">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="text-uppercase text-info fw-bold">New Users (30 days)</h6>
                                        <h2 class="mb-0">{{ $newUsers }}</h2>
                                    </div>
                                    <i class="fas fa-user-plus fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="row mt-4">
                    <div class="col-md-6">
                        <h6 class="fw-bold mb-3">Users by Role</h6>
                        <div class="chart-container" style="position: relative; height:300px;">
                            <canvas id="roleChart"></canvas>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h6 class="fw-bold mb-3">User Registration Trend</h6>
                        <div class="chart-container" style="position: relative; height:300px;">
                            <canvas id="registrationChart"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Role Chart
        var roleCtx = document.getElementById('roleChart').getContext('2d');
        var roleChart = new Chart(roleCtx, {
            type: 'pie',
            data: {
                labels: ['Public Users', 'Agency Users', 'MCMC Users'],
                datasets: [{
                    data: [{{ $publicUsers }}, {{ $agencyUsers }}, {{ $mcmcUsers }}],
                    backgroundColor: [
                        'rgba(78, 115, 223, 0.8)',
                        'rgba(28, 200, 138, 0.8)',
                        'rgba(54, 185, 204, 0.8)'
                    ],
                    borderColor: [
                        'rgb(78, 115, 223)',
                        'rgb(28, 200, 138)',
                        'rgb(54, 185, 204)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        position: 'right'
                    }
                }
            }
        });
        
        // Registration Chart
        var registrationCtx = document.getElementById('registrationChart').getContext('2d');
        var registrationChart = new Chart(registrationCtx, {
            type: 'line',
            data: {
                labels: {!! json_encode($months) !!},
                datasets: [{
                    label: 'New Registrations',
                    data: {!! json_encode($registrationCounts) !!},
                    backgroundColor: 'rgba(78, 115, 223, 0.05)',
                    borderColor: 'rgba(78, 115, 223, 1)',
                    borderWidth: 2,
                    pointBackgroundColor: 'rgba(78, 115, 223, 1)',
                    pointBorderColor: '#fff',
                    pointRadius: 4,
                    pointHoverRadius: 6,
                    fill: true,
                    tension: 0.3
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    y: {
                        beginAtZero: true,
                        ticks: {
                            precision: 0
                        }
                    }
                }
            }
        });
    });
</script>
@endsection